name: 🚀 Deploy Suzu Blog to Server (Build & Upload)

on:
  # ! Uncomment the following lines
  # ! to enable automatic deployment on push to main branch
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      ref:
        description: Branch to deploy
        required: false
        default: blog

permissions:
  contents: read

jobs:
  server-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref_name }}
          fetch-depth: 1

      - name: 📦 Set up Node.js and pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --ignore-scripts]

      - name: 💾 Cache .next/cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: ✅ Build Project
        run: pnpm run build

      - name: 📦 Package build files
        run: |
          tar --exclude=".next/cache" -czf build.tar.gz \
            .next \
            public \
            package.json \
            pnpm-lock.yaml \
            .node-version \
            LICENSE
          echo "📦 Archive size:"
          du -sh build.tar.gz

      - name: 📤 Upload build to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: build.tar.gz
          target: /data/apps/SuzuBlog

      # ! Check `.github/examples/deploy.sh` for the deployment script
      # ! We use nvm, pm2, and pnpm for deployment
      - name: 🛠️ SSH Run deploy.sh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /data/apps/SuzuBlog
            ./deploy.sh
